### ISSUE TITLE
侧边栏可以加一个toggle的图标吗？

### ISSUE THREAD

**Issue by weituotian** [iPeng6/docsify-sidebar-collapse#10]
想加一个展开，收缩的图标，请问怎么实现呢？太难了啊

**Comment by iPeng6** [comment]
左下角本来就有个收起的侧边栏的图标

**Comment by weituotian** [comment]
我是在目录层加了一个箭头
![image](https://user-images.githubusercontent.com/7270968/89876060-b5fb4a00-dbf0-11ea-8e4e-c8eaff648fd5.png)

**Comment by iPeng6** [comment]
这个插件支持 文件夹收起展开，加图标要自己写样式

**Comment by zszdevelop** [comment]
我也遇到了这个问题，有样式范例吗？

**Comment by iPeng6** [comment]
试试看，样式实现的一个箭头展开收起
```css
.sidebar-nav li {
  position: relative;
  margin: 0;
  cursor: pointer;
}

.sidebar-nav ul:not(.app-sub-sidebar) > li::before {
  content: '';
  display: block;
  position: absolute;
  top: 11px;
  left: -12px;
  height: 6px;
  width: 6px;
  border-right: 1px solid #505d6b;
  border-bottom: 1px solid #505d6b;
  transform: rotate(-45deg);
  transition: transform 0.1s;
}

.sidebar-nav ul:not(.app-sub-sidebar) > li.open::before {
  transform: rotate(45deg);
}

.sidebar-nav ul:not(.app-sub-sidebar) > li.collapse::before {
  transform: rotate(-45deg);
}
```

**Comment by zszdevelop** [comment]
> 试试看，样式实现的一个箭头展开收起
> 
> ```css
> .sidebar-nav li {
>   position: relative;
>   margin: 0;
>   cursor: pointer;
> }
> 
> .sidebar-nav ul:not(.app-sub-sidebar) > li::before {
>   content: '';
>   display: block;
>   position: absolute;
>   top: 11px;
>   left: -12px;
>   height: 6px;
>   width: 6px;
>   border-right: 1px solid #505d6b;
>   border-bottom: 1px solid #505d6b;
>   transform: rotate(-45deg);
>   transition: transform 0.1s;
> }
> 
> .sidebar-nav ul:not(.app-sub-sidebar) > li.open::before {
>   transform: rotate(45deg);
> }
> 
> .sidebar-nav ul:not(.app-sub-sidebar) > li.collapse::before {
>   transform: rotate(-45deg);
> }
> ```

可行，赞！！！
如果能加上没有子目录不显示箭头就好了

**Comment by iPeng6** [comment]
js更新到1.1.5版，样式参考 src/sidebar.css

```css
.sidebar-nav li {
  position: relative;
  margin: 0;
  cursor: pointer;
}

.sidebar-nav ul:not(.app-sub-sidebar) > li:not(.file)::before {
  content: '';
  display: block;
  position: absolute;
  top: 11px;
  left: -12px;
  height: 6px;
  width: 6px;
  border-right: 1px solid #505d6b;
  border-bottom: 1px solid #505d6b;
  transform: rotate(-45deg);
  transition: transform 0.1s;
}

.sidebar-nav ul:not(.app-sub-sidebar) > li.open::before {
  transform: rotate(45deg);
}

.sidebar-nav ul:not(.app-sub-sidebar) > li.collapse::before {
  transform: rotate(-45deg);
}
```
