### ISSUE TITLE
移动设备无法保持侧栏打开状态

### ISSUE THREAD

**Issue by Ares-X** [iPeng6/docsify-sidebar-collapse#13]
https://ares-x.com/wiki

移动设备上点击侧栏的任何标题后都会恢复到阅读模式，需要重新打开侧栏选择下级内容

device: iphone 6s plus
ios version: 13.7

**Comment by iPeng6** [comment]
我自己搞了一些样式处理了 没有加入到插件了
```css
<style>
@media screen and (max-width: 768px) {
  .content {
    padding: 0;
  }
  .markdown-section {
    padding: 16px;
  }
  /* pin */
  .sidebar-pin {
    position: fixed;
    bottom: 5px;
    border: none;
    padding: 10px;
    width: 30px;
    height: 30px;
    background: transparent;
  }
}
</style>
```
```js
<script>
      function togglePin() {
        let pin = localStorage.getItem('pin')
        pin = pin === 'true'
        localStorage.setItem('pin', !pin)
        if (pin) {
          document.querySelector('.sidebar').style.transform = 'translateX(0)'
          document.querySelector('.content').style.transform = 'translateX(0)'
        } else {
          document.querySelector('.sidebar').style.transform = 'translateX(300px)'
          document.querySelector('.content').style.transform = 'translateX(300px)'
        }
      }
      window.addEventListener('load', () => {
        const content = document.querySelector('.content')
        document.body.onclick = content.onclick = (e) => {
          if (e.target === document.body || e.currentTarget === content) {
            if (localStorage.getItem('pin') === 'true') {
              togglePin()
            }
          }
        }
      })
    </script>
```
```html
<body>
    <div id="app"></div>
    <!-- 自定义一个透明按钮覆盖默认收起边栏的按钮-->
    <button class="sidebar-pin" onclick="togglePin()"></button>
```
