### ISSUE TITLE
Clicking space between arrow and text leads to collapsing higher-level menu

### ISSUE THREAD

**Issue by volsko01** [iPeng6/docsify-sidebar-collapse#45]
## Steps to reproduce

<ol>
  <li>Open the second level menu (in our case it's 'Devops')</li>
  <li>Click space between arrow and 'Devops'</li>
  <li>Observe that 'Documentation' menu is collapsed</li>
</ol>

**Expected behaviour**: Only current level menu (in our case it's 'Devops' menu) should be collapsed.

![example](https://github.com/iPeng6/docsify-sidebar-collapse/assets/151513570/fb4a38dc-6f4b-4eca-901d-d99c9af0f1fd)

**Comment by PenNameLuXun** [comment]
you can use css to avoid :
> Add `li.folder{padding-left: 4px;}` to the end of the `vue.css` file.

> in file `sidebar.min.css`,find `.sidebar-nav ul:not(.app-sub-sidebar)>li:not(.file)::before` ,adjust the attri `left` to `-7px`:

```css
.sidebar-nav ul:not(.app-sub-sidebar)>li:not(.file)::before{content:'';display:block;position:absolute;top:11px;left:-7px;height:6px;width:6px;border-right:1px solid #505d6b;border-bottom:1px solid #505d6b;transform:rotate(-45deg);transition:transform .1s}
```
