### ISSUE TITLE
不支持docsify-themeable 这个主题

### ISSUE THREAD

**Issue by 5sdba** [iPeng6/docsify-sidebar-collapse#6]
引用以后显示的不明显
![image](https://user-images.githubusercontent.com/19336613/72592078-bbcfcc00-393c-11ea-9474-e3be8a17977c.png)
目录颜色没有显示出来，没有特效

**Comment by iPeng6** [comment]
1.  目录本身需要指向一个md文件才会有 目录的箭头
2. 目录具有子内容的时候才会高亮，点击才会展开

另外目录箭头方向有一些问题，可以自定义css 修复

```css
/* fix black theme fold arrow */

.sidebar-nav li > a[href^='#/']:not([href*='?id=']):not(:only-child) {
  background-image: var(
    --sidebar-nav-pagelink-background-image--collapse,
    var(
      --sidebar-nav-pagelink-background-image--loaded,
      var(--sidebar-nav-pagelink-background-image)
    )
  );
  background-position: var(
    --sidebar-nav-pagelink-background-position--collapse,
    var(
      --sidebar-nav-pagelink-background-position--loaded,
      var(--sidebar-nav-pagelink-background-image)
    )
  );
}

.sidebar-nav li.open > a[href^='#/']:not([href*='?id=']):not(:only-child) {
  background-image: var(
    --sidebar-nav-pagelink-background-image--active,
    var(
      --sidebar-nav-pagelink-background-image--loaded,
      var(--sidebar-nav-pagelink-background-image)
    )
  );
  background-position: var(
    --sidebar-nav-pagelink-background-position--active,
    var(
      --sidebar-nav-pagelink-background-position--loaded,
      var(--sidebar-nav-pagelink-background-image)
    )
  );
}
```

**Comment by 5sdba** [comment]
ok,谢谢大佬。

**Comment by CN-GuoZiyang** [comment]
你好，目前这个解决方法已经失效，请问有别的解决方案吗

**Comment by CorniiDog** [comment]
With thanks to what is above, and some minor adjustments:

（翻译）感谢以上内容，并进行了一些小调整:

```css
/* fix black theme fold arrow */
    .sidebar-nav li > a[href^='#/']:not([href*='?id=']):not(:only-child) {
      background-image: var(
        --sidebar-nav-pagelink-background-image--collapse,
        var(
          --sidebar-nav-pagelink-background-image--loaded,
          var(--sidebar-nav-pagelink-background-image)
        )
      );
      background-position: var(
        --sidebar-nav-pagelink-background-position--collapse,
        var(
          --sidebar-nav-pagelink-background-position--loaded,
          var(--sidebar-nav-pagelink-background-image)
        )
      );
    }

    .sidebar-nav li.open > a[href^='#/']:not([href*='?id=']):not(:only-child) {
      background-image: var(
        --sidebar-nav-pagelink-background-image--active,
        var(
          --sidebar-nav-pagelink-background-image--loaded,
          var(--sidebar-nav-pagelink-background-image)
        )
      );
      background-position: var(
        --sidebar-nav-pagelink-background-position--active,
        var(
          --sidebar-nav-pagelink-background-position--loaded,
          var(--sidebar-nav-pagelink-background-image)
        )
      );
    }

    /* Remove built-in background arrow from collapsed/expanded states */
    .sidebar-nav li > a[href^='#/']:not([href*='?id=']):not(:only-child),
    .sidebar-nav li.open > a[href^='#/']:not([href*='?id=']):not(:only-child) {
      background-image: none !important;
      padding-left: 0.0em !important; /* Adjust to match links without arrows */
    }

    

    .alert.callout {
      border-color: transparent;
      background: rgba(0, 0, 0, 0.089);
      border-radius: 0.15rem;
    }

    .app-sub-sidebar,
    .app-sub-sidebar li {
      margin: 0 !important;
      padding: 0 !important;
    }

    /* Prepend “+” to every sub-sidebar link */
    .app-sub-sidebar li a::before {
      content: "+" !important;
      display: inline-block;
      width: 1em;
      text-align: left;
      margin-right: 0em;
    }

    /* When that item is the active anchor, switch to “–” */
    .app-sub-sidebar li.active > a::before {
      content: "-" !important;
    }

    /* Remove left‐padding/indent on the sub-sidebar list and links */
    .app-sub-sidebar ul {
      margin: 0 !important;
      padding: 0 !important;
    }
    .app-sub-sidebar li {
      margin: 0 !important;
      padding: 0 !important;
    }
    .app-sub-sidebar a.section-link {
      margin-left: 0 !important;
      padding-left: 0 !important;
    }
```
